// src/components/toolbar/AdminToolbar.vue
<template>
  <!-- Title -->
  <div class="flex-1 flex items-center gap-2 min-w-0">
    <router-link
      v-if="screen.gtXs"
      to="/"
      class="text-base font-semibold whitespace-nowrap link hover:opacity-80 transition-opacity"
    >
      {{ $route.meta.title }}
    </router-link>
  </div>

  <!-- Indeterminate progress bar at header bottom -->
  <Teleport to="body">
    <div v-if="busy" class="fixed top-14 left-0 right-0 z-30 h-0.5 overflow-hidden">
      <AppProgress indeterminate color="warning" :height="2" />
    </div>
  </Teleport>

  <!-- Admin tab switcher -->
  <div class="flex rounded-lg overflow-hidden border border-gray-300 dark:border-gray-600 ml-2">
    <button
      v-for="tab in tabs"
      :key="tab.name"
      :class="[
        'flex items-center gap-1.5 px-3 py-1.5 text-sm transition-colors',
        adminTab === tab.name
          ? 'bg-primary text-white'
          : 'text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800',
      ]"
      :title="tab.label"
      @click="adminTab = tab.name"
    >
      <AppIcon :name="tab.icon" class="w-4 h-4" />
      <span v-if="screen.gtXs" class="hidden sm:inline">{{ tab.label }}</span>
    </button>
  </div>
</template>

<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { useAppStore } from '../../stores/app'
import { useScreen } from '../../composables/useScreen'
import AppProgress from '../atoms/AppProgress.vue'
import AppIcon from '../atoms/AppIcon.vue'

const app = useAppStore()
const { busy, adminTab } = storeToRefs(app)
const screen = useScreen()

const tabs = [
  { name: 'repair', icon: 'construction', label: 'Repair' },
  { name: 'meta', icon: 'schema', label: 'Metadata' },
  { name: 'users', icon: 'group', label: 'Users' },
  { name: 'messages', icon: 'chat', label: 'Messages' },
] as const
</script>

// src/components/toolbar/AdminToolbar.tsx
'use client'

import React from 'react'
import Link from 'next/link'
import { useAppStore } from '../../stores/appStore'
import AppProgress from '../atoms/AppProgress'
import AppIcon from '../atoms/AppIcon'

export const AdminToolbar: React.FC = () => {
  const busy = useAppStore((state) => state.busy)
  const adminTab = useAppStore((state) => state.adminTab)
  const setAdminTab = useAppStore((state) => state.setAdminTab)

  const tabs = [
    { name: 'repair', icon: 'construction', label: 'Repair' },
    { name: 'meta', icon: 'schema', label: 'Metadata' },
    { name: 'users', icon: 'group', label: 'Users' },
  ] as const

  return (
    <>
      {/* Title */}
      <div className="flex-1 flex items-center gap-2 min-w-0">
        <Link
          href="/"
          className="text-base font-semibold whitespace-nowrap link hover:opacity-80 transition-opacity"
        >
          Admin.
        </Link>
      </div>

      {/* Progress bar below the header */}
      {busy && (
        <div className="fixed top-14 left-0 right-0 z-30 h-0.5 overflow-hidden">
          <AppProgress indeterminate color="warning" height={2} />
        </div>
      )}

      {/* Admin tab switcher */}
      <div className="flex rounded-lg overflow-hidden border border-gray-300 dark:border-gray-600 ml-2">
        {tabs.map((tab) => (
          <button
            key={tab.name}
            className={`flex items-center gap-1.5 px-3 py-1.5 text-sm transition-colors ${
              adminTab === tab.name
                ? 'bg-primary text-white'
                : 'text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800'
            }`}
            title={tab.label}
            onClick={() => setAdminTab(tab.name)}
          >
            <AppIcon name={tab.icon} className="w-4 h-4" />
            <span className="hidden md:inline">{tab.label}</span>
          </button>
        ))}
      </div>
    </>
  )
}

export default AdminToolbar
