// src/components/sidebar/Sidebar.vue
<template>
  <div class="flex flex-col h-full mt-4">
    <Menu />
    <div class="grow"></div>
    <ManageSelection v-if="route.name === 'list'" />
    <SendMessage v-if="route.name === 'admin' || route.name === 'add'" />
  </div>
</template>

<script setup lang="ts">
import { useRoute } from 'vue-router'
import Menu from './Menu.vue'
import ManageSelection from './ManageSelection.vue'
import SendMessage from './SendMessage.vue'

const route = useRoute()
</script>

// src/components/layouts/Sidebar.tsx
'use client'

import React from 'react'
import { usePathname } from 'next/navigation'
import Menu from '@/components/Menu'
import ManageSelection from '@/components/ManageSelection'
import SendMessage from '@/components/SendMessage'

interface SidebarProps {
  onCloseMobile?: () => void
}

export const Sidebar: React.FC<SidebarProps> = ({ onCloseMobile }) => {
  const pathname = usePathname()

  return (
    <div className="flex flex-col h-full mt-4">
      <Menu onLinkClick={onCloseMobile} />
      <div className="grow"></div>
      {pathname === '/list' && <ManageSelection />}
      {(pathname === '/admin' || pathname === '/add') && <SendMessage />}
    </div>
  )
}

export default Sidebar
