// src/components/tab/UsersTab.vue
<template>
  <ErrorBanner :inquiry="!busy && error != ''">
    <template #title>{{ error }}</template>
  </ErrorBanner>

  <AppBanner color="info" class="p-4">
    <div class="flex items-center gap-3">
      <AppIcon name="sym_r_person" class="w-6 h-6" />
      <span class="text-lg font-semibold">Users</span>
    </div>
  </AppBanner>

  <div class="px-4 pb-4">
    <LocalSearch v-model="search" label="Search users" :options="nickValues" />
  </div>

  <div class="p-4 overflow-y-auto" style="height: 65vh">
    <div :class="['flex flex-col gap-2', screen.xs ? 'gap-1' : '']">
      <template v-if="busy">
        <div
          v-for="n in 5"
          :key="n"
          class="flex items-center p-3 bg-gray-100 dark:bg-gray-800 rounded-lg animate-pulse"
        >
          <div class="flex-shrink-0 w-8 h-8 bg-gray-300 dark:bg-gray-700 rounded-full mr-3"></div>
          <div class="flex-grow">
            <div class="h-4 bg-gray-300 dark:bg-gray-700 rounded w-1/3 mb-2"></div>
            <div class="h-3 bg-gray-200 dark:bg-gray-800 rounded w-2/3"></div>
          </div>
          <div v-if="screen.gtXs" class="flex gap-1 ml-auto">
            <div class="w-4 h-4 bg-gray-300 dark:bg-gray-700 rounded-full"></div>
            <div class="w-4 h-4 bg-gray-300 dark:bg-gray-700 rounded-full"></div>
          </div>
          <div class="flex gap-1 ml-auto" :class="screen.xs ? 'flex-col' : 'flex-row'">
            <div class="w-4 h-4 bg-gray-300 dark:bg-gray-700 rounded"></div>
            <div class="w-4 h-4 bg-gray-300 dark:bg-gray-700 rounded"></div>
            <div class="w-4 h-4 bg-gray-300 dark:bg-gray-700 rounded"></div>
          </div>
        </div>
      </template>

      <div
        v-for="item in filteredResult"
        :key="item.uid"
        v-else
        class="flex items-center p-3 bg-white dark:bg-gray-800 rounded-lg shadow-sm hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
      >
        <div class="flex-shrink-0 mr-3">
          <AppBadge color="warning" textColor="black" class="text-sm px-2 py-1">
            {{ contribution(item.nick) }}
          </AppBadge>
        </div>

        <div class="flex-grow">
          <div class="flex items-center gap-1 text-base font-semibold">
            {{ item.nick || '???' }}
            <AppButton
              v-if="contribution(item.nick) === 0"
              flat
              round
              dense
              icon="sym_r_edit"
              color="primary"
              @click="openNickDialog(item)"
            >
              <span class="text-xs">Change nickname</span>
            </AppButton>
            <AppButton
              v-if="contribution(item.nick) === 0"
              flat
              round
              dense
              icon="sym_r_delete"
              color="negative"
              @click="confirmDeleteUser(item)"
            >
              <span class="text-xs">Delete user</span>
            </AppButton>
          </div>
          <div class="text-xs text-gray-500">{{ item.email }}</div>
          <div class="text-xs text-gray-400">subscribed {{ ageDays(item.timestamp) }} days ago</div>
        </div>

        <div v-if="screen.gtXs" class="flex-shrink-0 ml-3 flex gap-1">
          <template v-if="item.timestamps?.length">
            <AppBadge
              v-for="(timestamp, index) in item.timestamps"
              :key="index"
              color="secondary"
              textColor="black"
            >
              {{ ageDays(timestamp) }}
            </AppBadge>
          </template>
          <AppBadge v-else color="grey" textColor="black">no tokens</AppBadge>
        </div>

        <div
          class="flex-shrink-0 ml-3 flex gap-x-3"
          :class="screen.xs ? 'flex-col gap-y-1' : 'flex-row'"
        >
          <label class="flex items-center gap-1 cursor-pointer">
            <input
              type="checkbox"
              v-model="item.isAdmin"
              :disabled="user?.email === item.email || !item.nick"
              class="w-4 h-4 rounded border-gray-300 text-negative focus:ring-negative"
              @change="toggleAdmin(item, item.isAdmin)"
            />
            <span class="text-xs">Admin</span>
          </label>
          <label class="flex items-center gap-1 cursor-pointer">
            <input
              type="checkbox"
              v-model="item.isAuthorized"
              :disabled="!item.nick"
              class="w-4 h-4 rounded border-gray-300 text-primary focus:ring-primary"
              @change="item.nick ? auth.updateUser(item, 'isAuthorized') : null"
            />
            <span class="text-xs">Editor</span>
          </label>
          <label class="flex items-center gap-1 cursor-pointer">
            <input
              type="checkbox"
              v-model="item.allowPush"
              :disabled="!item.nick"
              class="w-4 h-4 rounded border-gray-300 text-secondary focus:ring-secondary"
              @change="item.nick ? auth.updateUser(item, 'allowPush') : null"
            />
            <span class="text-xs">Push</span>
          </label>
        </div>
      </div>
    </div>
  </div>

  <!-- Delete User Confirmation Dialog -->
  <Dialog :open="showDeleteDialog" @close="showDeleteDialog = false" class="relative z-50">
    <div class="fixed inset-0 bg-black/30" aria-hidden="true" />
    <div class="fixed inset-0 flex items-center justify-center p-4">
      <DialogPanel
        class="bg-white dark:bg-gray-800 rounded-xl shadow-xl w-full max-w-md overflow-hidden"
      >
        <div class="p-6">
          <div class="text-lg font-bold mb-2">Delete user?</div>
          <p class="text-gray-600 dark:text-gray-400">
            Remove <strong class="text-black dark:text-white">{{ userToDelete?.nick }}</strong> ({{
              userToDelete?.email
            }})? This cannot be undone.
          </p>
        </div>
        <div class="flex justify-end gap-3 p-6 border-t border-gray-100 dark:border-gray-700">
          <AppButton flat label="Cancel" @click="showDeleteDialog = false" />
          <AppButton flat label="Delete" color="negative" @click="doDeleteUser" />
        </div>
      </DialogPanel>
    </div>
  </Dialog>

  <!-- Nickname Edit Dialog -->
  <Dialog :open="showNickDialog" @close="showNickDialog = false" class="relative z-50">
    <div class="fixed inset-0 bg-black/30" aria-hidden="true" />
    <div class="fixed inset-0 flex items-center justify-center p-4">
      <DialogPanel
        class="bg-white dark:bg-gray-800 rounded-xl shadow-xl w-full max-w-md overflow-hidden"
      >
        <div class="p-6">
          <div class="text-lg font-bold mb-4">Change nickname for {{ userToEdit?.email }}</div>
          <AppInput
            v-model="tempNick"
            label="New nickname"
            autofocus
            clearable
            :rules="[
              (v: string) => !!v || 'Nickname cannot be empty',
              (v: string) => !nickValues.includes(v) || 'Nickname already taken',
            ]"
            @keyup.enter="saveNick"
          />
        </div>
        <div class="flex justify-end gap-3 p-6 border-t border-gray-100 dark:border-gray-700">
          <AppButton flat label="Cancel" @click="showNickDialog = false" />
          <AppButton
            flat
            label="Save"
            @click="saveNick"
            :disabled="!tempNick || nickValues.includes(tempNick)"
          />
        </div>
      </DialogPanel>
    </div>
  </Dialog>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { storeToRefs } from 'pinia'
import { useAppStore } from '../../stores/app'
import { useValuesStore } from '../../stores/values'
import { useUserStore } from '../../stores/user'

import ErrorBanner from '../ErrorBanner.vue'
import type { UsersAndDevices } from '../../helpers/models'
import type { Timestamp } from 'firebase/firestore'

import LocalSearch from '../LocalSearch.vue'
import notify from '../../helpers/notify'

import AppBanner from '../atoms/AppBanner.vue'
import AppBadge from '../atoms/AppBadge.vue'
import AppButton from '../atoms/AppButton.vue'
import AppInput from '../atoms/AppInput.vue'
import AppIcon from '../atoms/AppIcon.vue'
import { Dialog, DialogPanel } from '@headlessui/vue'
import { useScreen } from '../../composables/useScreen'

const app = useAppStore()
const meta = useValuesStore()
const auth = useUserStore()
const screen = useScreen()

const { busy, error } = storeToRefs(app)
const { user } = storeToRefs(auth)
const { nickValues, nickWithCount } = storeToRefs(meta)
const result = ref<UsersAndDevices[]>([])
const search = ref('')

const filteredResult = computed(() => {
  if (!search.value) return result.value
  const query = search.value.toLowerCase()
  return result.value.filter(
    (item) => item.nick.toLowerCase().includes(query) || item.email.toLowerCase().includes(query),
  )
})

const adminCount = computed(() => result.value.filter((u) => u.isAdmin).length)

const showNickDialog = ref(false)
const userToEdit = ref<UsersAndDevices | null>(null)
const tempNick = ref('')

const showDeleteDialog = ref(false)
const userToDelete = ref<UsersAndDevices | null>(null)

const confirmDeleteUser = (user: UsersAndDevices) => {
  userToDelete.value = user
  showDeleteDialog.value = true
}

const doDeleteUser = async () => {
  if (userToDelete.value) {
    if (userToDelete.value.isAdmin && adminCount.value === 1) {
      notify({ type: 'negative', message: 'Cannot delete the only admin user' })
      showDeleteDialog.value = false
      return
    }
    await auth.deleteUser(userToDelete.value.uid)
    showDeleteDialog.value = false
    await fetchList()
  }
}

const fetchList = async () => {
  busy.value = true
  error.value = ''
  const subscribersAndDevices = await auth.fetchUsersAndDevices()
  result.value = subscribersAndDevices ?? []
  busy.value = false
  error.value = result.value.length === 0 ? 'No subscribers found' : ''
}

const openNickDialog = (user: UsersAndDevices) => {
  userToEdit.value = user
  tempNick.value = user.nick
  showNickDialog.value = true
}

const toggleAdmin = async (item: UsersAndDevices, val: boolean) => {
  const remainingAdmins = result.value.filter((u) => u.isAdmin).length
  if (!val && remainingAdmins === 0) {
    notify({ type: 'negative', message: 'Cannot remove the last administrator' })
    item.isAdmin = true
    return
  }
  await auth.updateUser(item, 'isAdmin')
}

const saveNick = async () => {
  if (userToEdit.value && tempNick.value) {
    userToEdit.value.nick = tempNick.value
    await auth.updateUser(userToEdit.value, 'nick')
    showNickDialog.value = false
  }
}

onMounted(fetchList)

const ageDays = (timestamp: Timestamp) => {
  const diff = Date.now() - timestamp.toMillis()
  return Math.floor(diff / 86400000)
}

const contribution = (nick: string) => {
  const entry = nickWithCount.value[nick]
  return entry ? entry : 0
}
</script>

// src/app/admin/UsersTab.tsx
'use client'

import React, { useState, useEffect, useMemo } from 'react'
import { useUserStore } from '@/stores/userStore'
import { useValuesStore, selectNickValues, selectNickWithCount } from '@/stores/valuesStore'
import { useScreen } from '@/composables/useScreen'
import ErrorBanner from '@/components/ErrorBanner'
import LocalSearch from '@/components/LocalSearch'
import notify from '@/helpers/notify'
import AppBadge from '@/components/atoms/AppBadge'
import AppButton from '@/components/atoms/AppButton'
import AppInput from '@/components/atoms/AppInput'
import AppIcon from '@/components/atoms/AppIcon'
import AppDialog from '@/components/atoms/AppDialog'
import { getAgeDays, type DateInput } from '@/helpers'
import type { UsersAndDevices } from '@/helpers/models'

export const UsersTab: React.FC = () => {
  const user = useUserStore((state) => state.user)
  const fetchUsersAndDevices = useUserStore((state) => state.fetchUsersAndDevices)
  const updateUser = useUserStore((state) => state.updateUser)
  const deleteUser = useUserStore((state) => state.deleteUser)

  const nickValues = useValuesStore(selectNickValues)
  const nickWithCount = useValuesStore(selectNickWithCount)
  const screen = useScreen()

  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [result, setResult] = useState<UsersAndDevices[]>([])
  const [search, setSearch] = useState('')

  const [showNickDialog, setShowNickDialog] = useState(false)
  const [userToEdit, setUserToEdit] = useState<UsersAndDevices | null>(null)
  const [tempNick, setTempNick] = useState('')

  const [showDeleteDialog, setShowDeleteDialog] = useState(false)
  const [userToDelete, setUserToDelete] = useState<UsersAndDevices | null>(null)

  const filteredResult = useMemo(() => {
    if (!search) return result
    const query = search.toLowerCase()
    return result.filter(
      (item) =>
        (item.nick || '').toLowerCase().includes(query) ||
        (item.email || '').toLowerCase().includes(query),
    )
  }, [result, search])

  const adminCount = useMemo(() => {
    return result.filter((u) => u.isAdmin).length
  }, [result])

  const fetchList = async () => {
    setBusy(true)
    setError('')
    try {
      const subscribersAndDevices = await fetchUsersAndDevices()
      setResult(subscribersAndDevices ?? [])
      if (!subscribersAndDevices || subscribersAndDevices.length === 0) {
        setError('No subscribers found')
      }
    } catch (err) {
      console.error(err)
      setError('Failed to fetch subscribers')
    } finally {
      setBusy(false)
    }
  }

  useEffect(() => {
    void fetchList()
  }, [])

  const confirmDeleteUser = (u: UsersAndDevices) => {
    setUserToDelete(u)
    setShowDeleteDialog(true)
  }

  const doDeleteUser = async () => {
    if (userToDelete) {
      if (userToDelete.isAdmin && adminCount === 1) {
        notify({ type: 'negative', message: 'Cannot delete the only admin user' })
        setShowDeleteDialog(false)
        return
      }
      try {
        await deleteUser(userToDelete.uid)
        setShowDeleteDialog(false)
        await fetchList()
      } catch (err) {
        notify({ type: 'negative', message: `Failed to delete: ${err}` })
      }
    }
  }

  const openNickDialog = (u: UsersAndDevices) => {
    setUserToEdit(u)
    setTempNick(u.nick || '')
    setShowNickDialog(true)
  }

  const toggleAdmin = async (item: UsersAndDevices, val: boolean) => {
    const nextResult = result.map((u) => {
      if (u.uid === item.uid) {
        return { ...u, isAdmin: val }
      }
      return u
    })
    const remainingAdmins = nextResult.filter((u) => u.isAdmin).length
    if (!val && remainingAdmins === 0) {
      notify({ type: 'negative', message: 'Cannot remove the last administrator' })
      return
    }

    try {
      const updatedItem = { ...item, isAdmin: val }
      await updateUser(updatedItem, 'isAdmin')
      setResult(nextResult)
    } catch (err) {
      notify({ type: 'negative', message: `Failed to update: ${err}` })
    }
  }

  const handleAdminCheckboxChange = (checked: boolean, item: UsersAndDevices) => {
    void toggleAdmin(item, checked)
  }

  const toggleEditor = async (item: UsersAndDevices, val: boolean) => {
    if (!item.nick) return
    try {
      const updatedItem = { ...item, isAuthorized: val }
      await updateUser(updatedItem, 'isAuthorized')
      setResult((prev) => prev.map((u) => (u.uid === item.uid ? updatedItem : u)))
    } catch (err) {
      notify({ type: 'negative', message: `Failed to update: ${err}` })
    }
  }

  const togglePush = async (item: UsersAndDevices, val: boolean) => {
    if (!item.nick) return
    try {
      const updatedItem = { ...item, allowPush: val }
      await updateUser(updatedItem, 'allowPush')
      setResult((prev) => prev.map((u) => (u.uid === item.uid ? updatedItem : u)))
    } catch (err) {
      notify({ type: 'negative', message: `Failed to update: ${err}` })
    }
  }

  const saveNick = async () => {
    if (userToEdit && tempNick) {
      const updatedItem = { ...userToEdit, nick: tempNick }
      try {
        await updateUser(updatedItem, 'nick')
        setResult((prev) => prev.map((u) => (u.uid === userToEdit.uid ? updatedItem : u)))
        setShowNickDialog(false)
      } catch (err) {
        notify({ type: 'negative', message: `Failed to save nickname: ${err}` })
      }
    }
  }

  const ageDays = (timestamp: unknown) => getAgeDays(timestamp as DateInput)

  const contribution = (nick: string) => {
    const entry = nickWithCount[nick]
    return entry ? entry : 0
  }

  return (
    <>
      <ErrorBanner inquiry={!busy && error !== ''} title={error} />

      {/* Search */}
      <div className="px-4 py-3 border-b border-gray-200 dark:border-gray-700">
        <LocalSearch
          modelValue={search}
          onChangeValue={setSearch}
          label="Search users"
          options={nickValues}
        />
      </div>

      <div className="p-4 overflow-y-auto" style={{ height: '65vh' }}>
        <div className={`flex flex-col gap-2 ${screen.xs ? 'gap-1' : ''}`}>
          {busy
            ? Array.from({ length: 5 }).map((_, n) => (
                <div
                  key={n}
                  className="flex items-center p-3 bg-gray-100 dark:bg-gray-800 rounded-lg animate-pulse"
                >
                  <div className="shrink-0 w-8 h-8 bg-gray-300 dark:bg-gray-700 rounded-full mr-3"></div>
                  <div className="grow">
                    <div className="h-4 bg-gray-300 dark:bg-gray-700 rounded w-1/3 mb-2"></div>
                    <div className="h-3 bg-gray-200 dark:bg-gray-800 rounded w-2/3"></div>
                  </div>
                  {screen.gtXs && (
                    <div className="flex flex-wrap gap-1 ml-auto max-w-xs">
                      <div className="w-4 h-4 bg-gray-300 dark:bg-gray-700 rounded-full"></div>
                      <div className="w-4 h-4 bg-gray-300 dark:bg-gray-700 rounded-full"></div>
                    </div>
                  )}
                  <div className={`flex gap-1 ml-auto ${screen.xs ? 'flex-col' : 'flex-row'}`}>
                    <div className="w-4 h-4 bg-gray-300 dark:bg-gray-700 rounded"></div>
                    <div className="w-4 h-4 bg-gray-300 dark:bg-gray-700 rounded"></div>
                    <div className="w-4 h-4 bg-gray-300 dark:bg-gray-700 rounded"></div>
                  </div>
                </div>
              ))
            : filteredResult.map((item) => (
                <div
                  key={item.uid}
                  className="flex items-center p-3 bg-white dark:bg-gray-800 rounded-lg shadow-sm hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
                >
                  <div className="shrink-0 mr-3">
                    <AppBadge color="warning" textColor="black" className="text-sm px-2 py-1">
                      {contribution(item.nick || '')}
                    </AppBadge>
                  </div>

                  <div className="grow">
                    <div className="flex items-center gap-1 text-base font-semibold flex-wrap">
                      <span>{item.nick || '???'}</span>
                      {contribution(item.nick || '') === 0 && (
                        <>
                          <AppButton
                            flat
                            onClick={() => openNickDialog(item)}
                            color="primary"
                            className="p-1!"
                            title="Change nickname"
                          >
                            <AppIcon name="edit" className="w-4 h-4" />
                            <span className="text-xs ml-1 font-normal">Change</span>
                          </AppButton>
                          <AppButton
                            flat
                            onClick={() => confirmDeleteUser(item)}
                            color="negative"
                            className="p-1!"
                            title="Delete user"
                          >
                            <AppIcon name="delete" className="w-4 h-4" />
                            <span className="text-xs ml-1 font-normal">Delete</span>
                          </AppButton>
                        </>
                      )}
                    </div>
                    <div className="text-xs text-gray-500">{item.email}</div>
                    <div className="text-xs text-gray-400">
                      subscribed {ageDays(item.timestamp)} days ago
                    </div>
                  </div>

                  {screen.gtXs && (
                    <div className="shrink-0 ml-3 max-w-50">
                      <div className="flex flex-wrap gap-1 justify-end">
                        {item.timestamps && item.timestamps.length > 0 ? (
                          item.timestamps.map((timestamp, index) => (
                            <AppBadge key={index} color="secondary" textColor="dark">
                              {ageDays(timestamp)}
                            </AppBadge>
                          ))
                        ) : (
                          <AppBadge color="secondary" textColor="dark">
                            no tokens
                          </AppBadge>
                        )}
                      </div>
                    </div>
                  )}

                  <div
                    className={`shrink-0 ml-3 flex gap-x-3 ${screen.xs ? 'flex-col gap-y-1' : 'flex-row'}`}
                  >
                    <label className="flex items-center gap-1 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={!!item.isAdmin}
                        disabled={user?.email === item.email || !item.nick}
                        className="w-4 h-4 rounded border-gray-300 text-negative focus:ring-negative"
                        onChange={(e) => handleAdminCheckboxChange(e.target.checked, item)}
                      />
                      <span className="text-xs">Admin</span>
                    </label>
                    <label className="flex items-center gap-1 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={!!item.isAuthorized}
                        disabled={!item.nick}
                        className="w-4 h-4 rounded border-gray-300 text-primary focus:ring-primary"
                        onChange={(e) => void toggleEditor(item, e.target.checked)}
                      />
                      <span className="text-xs">Editor</span>
                    </label>
                    <label className="flex items-center gap-1 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={!!item.allowPush}
                        disabled={!item.nick}
                        className="w-4 h-4 rounded border-gray-300 text-secondary focus:ring-secondary"
                        onChange={(e) => void togglePush(item, e.target.checked)}
                      />
                      <span className="text-xs">Push</span>
                    </label>
                  </div>
                </div>
              ))}
        </div>
      </div>

      {/* Delete User Confirmation Dialog */}
      <AppDialog modelValue={showDeleteDialog} maxWidth="max-w-sm" onChange={setShowDeleteDialog}>
        <div className="p-6">
          <div className="text-lg font-bold mb-2">Delete user?</div>
          <p className="text-gray-600 dark:text-gray-400">
            Remove <strong>{userToDelete?.nick}</strong> ({userToDelete?.email})? This cannot be
            undone.
          </p>
          <div className="flex justify-end gap-3 mt-6">
            <AppButton flat label="Cancel" onClick={() => setShowDeleteDialog(false)} />
            <AppButton flat label="Delete" color="negative" onClick={doDeleteUser} />
          </div>
        </div>
      </AppDialog>

      {/* Nickname Edit Dialog */}
      <AppDialog modelValue={showNickDialog} maxWidth="max-w-sm" onChange={setShowNickDialog}>
        <div className="p-6">
          <div className="text-lg font-bold mb-4">Change nickname for {userToEdit?.email}</div>
          <AppInput
            modelValue={tempNick}
            onChangeValue={setTempNick}
            label="New nickname"
            autoFocus
            clearable
            onKeyUp={(e) => {
              if (e.key === 'Enter' && tempNick && !nickValues.includes(tempNick)) {
                void saveNick()
              }
            }}
          />
          {tempNick && nickValues.includes(tempNick) && (
            <p className="text-xs text-negative mt-1">Nickname already taken</p>
          )}
        </div>
        <div className="flex justify-end gap-3 p-6 border-t border-gray-100 dark:border-gray-700">
          <AppButton flat label="Cancel" onClick={() => setShowNickDialog(false)} />
          <AppButton
            flat
            label="Save"
            onClick={saveNick}
            disabled={!tempNick || nickValues.includes(tempNick)}
          />
        </div>
      </AppDialog>
    </>
  )
}

export default UsersTab
