// src/components/sidebar/Menu.tsx
'use client'

import React from 'react'
import { useUserStore } from '../../stores/userStore'
import MenuLink from './MenuLink'

interface MenuProps {
  onLinkClick?: () => void
}

export const Menu: React.FC<MenuProps> = ({ onLinkClick }) => {
  const user = useUserStore((state) => state.user)

  return (
    <nav className="mt-2 px-2 space-y-1">
      <MenuLink to="/" icon="sym_r_home" title="Start" onClick={onLinkClick} />

      <MenuLink
        to="/list"
        icon="sym_r_grid_view"
        title="Browse"
        subtitle="You can filter results"
        onClick={onLinkClick}
      />

      {user && user.isAuthorized && user.nick && (
        <MenuLink
          to="/add"
          icon="sym_r_add_a_photo"
          title="Add"
          subtitle="jpeg images less then 5 Mb"
          onClick={onLinkClick}
        />
      )}

      {user && user.isAdmin && (
        <MenuLink
          to="/admin"
          icon="sym_r_settings"
          title="Admin"
          subtitle="rebuild, repair, tags, subscribers"
          onClick={onLinkClick}
        />
      )}
    </nav>
  )
}

export default Menu

// src/components/Menu.vue
<template>
  <q-list dark>
    <q-item clickable @click="auth.signIn">
      <q-item-section avatar>
        <q-icon name="person" />
      </q-item-section>

      <q-item-section v-if="user && user.name">
        <q-item-label>Sign out</q-item-label>
        <q-item-label caption>{{ user.name }}</q-item-label>
      </q-item-section>
      <q-item-section v-else>
        <q-item-label>Sign in</q-item-label>
        <q-item-label caption>using your Google account</q-item-label>
      </q-item-section>
    </q-item>

    <q-item
      clickable
      v-ripple
      v-show="user && user.isAuthorized"
      to="/add"
      :active="$route.name === 'add'"
    >
      <q-item-section avatar>
        <q-icon name="add_circle" />
      </q-item-section>

      <q-item-section>
        <q-item-label>Add</q-item-label>
        <q-item-label caption>jpeg images less then 4 Mb</q-item-label>
      </q-item-section>
    </q-item>

    <q-item
      clickable
      v-ripple
      v-show="user && user.isAdmin"
      to="/admin"
      :active="$route.name === 'admin'"
    >
      <q-item-section avatar>
        <q-icon name="settings" />
      </q-item-section>

      <q-item-section>
        <q-item-label>Admin</q-item-label>
        <q-item-label caption>rebuild, repair, tags, subscribers</q-item-label>
      </q-item-section>
    </q-item>
  </q-list>
</template>

<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { useUserStore } from '../stores/user'

const auth = useUserStore()
const { user } = storeToRefs(auth)
</script>
