// src/components/PictureCard.tsx
import React, { useState, useMemo } from 'react'
import { U, formatDatum, openMaps } from '@/helpers'
import type { PhotoType } from '@/helpers/models'
import { useAppStore } from '@/stores/appStore'
import FileBroken from '@/components/FileBroken'
import AppIcon from '@/components/atoms/AppIcon'

interface PictureCardProps {
  rec: PhotoType
  onCarouselShow?: (filename: string) => void
  action?: React.ReactNode
}

export const PictureCard: React.FC<PictureCardProps> = ({ rec, onCarouselShow, action }) => {
  const searchBy = useAppStore((state) => state.searchBy)
  const [imgError, setImgError] = useState(false)

  const thumbUrl = useMemo(() => {
    return rec.thumb || rec.url
  }, [rec.thumb, rec.url])

  const isPublished = useMemo(() => {
    return (rec.kind === 'photo' && rec.thumb) || rec.kind === 'video'
  }, [rec.kind, rec.thumb])

  if (isPublished) {
    return (
      <div id={U + rec.filename} className="card group">
        {/* Thumbnail image with aspect ratio */}
        <div className="relative w-full overflow-hidden" style={{ paddingTop: '75%' }}>
          <img
            loading="lazy"
            src={thumbUrl}
            alt={rec.headline || rec.filename}
            className="absolute inset-0 w-full h-full object-cover cursor-pointer transition-transform duration-300 group-hover:scale-105"
            onClick={() => onCarouselShow && onCarouselShow(rec.filename)}
            onError={() => setImgError(true)}
          />
          {/* Broken image */}
          {imgError && <FileBroken />}
          {/* Video play overlay */}
          {rec.kind === 'video' && (
            <div className="absolute inset-0 flex items-center justify-center bg-black/20 pointer-events-none">
              <AppIcon name="play_circle" className="w-16 h-16 text-white/60 drop-shadow-lg" />
            </div>
          )}
        </div>

        {/* Action slot (edit button, checkbox) */}
        {action}

        {/* Caption */}
        <div className="px-3 py-1 text-sm font-medium truncate text-gray-900 dark:text-gray-100">
          {rec.headline}
        </div>
        <div className="flex items-center justify-between px-3 pb-2 text-xs text-gray-500 dark:text-gray-400">
          <span>
            <a
              href="#"
              className="link hover:text-secondary/80 transition-colors"
              onClick={(e) => {
                e.preventDefault()
                searchBy({ nick: rec.nick })
              }}
            >
              {rec.nick}
            </a>
            {', '}
            <a
              href="#"
              className="link hover:text-primary transition-colors"
              onClick={(e) => {
                e.preventDefault()
                searchBy({ year: rec.year, month: rec.month, day: rec.day })
              }}
            >
              {rec.date ? formatDatum(rec.date, 'DD.MM.YYYY HH:mm') : ''}
            </a>
          </span>
          {rec.loc && (
            <button
              className="hover:text-primary transition-colors"
              onClick={(e) => {
                e.stopPropagation()
                e.preventDefault()
                openMaps(rec.loc!)
              }}
            >
              <AppIcon name="my_location" className="w-5 h-5" />
            </button>
          )}
        </div>
      </div>
    )
  }

  // Unpublished (upload queue) card
  return (
    <div id={U + rec.filename} className="card">
      <div className="relative w-full overflow-hidden" style={{ paddingTop: '80%' }}>
        <img
          loading="lazy"
          src={rec.url}
          alt={rec.filename}
          className="absolute inset-0 w-full h-full object-cover"
          onError={() => setImgError(true)}
        />
        {imgError && <FileBroken />}
      </div>
      {action}
    </div>
  )
}

export default PictureCard

// src/components/Picture-Card.vue
<template>
  <q-card v-if="rec.thumb" :id="U + rec.filename" class="card" flat>
    <q-img
      loading="lazy"
      :ratio="5 / 4"
      :src="rec.thumb"
      @click="emit('carousel-show', rec.filename)"
      class="col cursor-pointer"
      no-spinner
    >
      <template #error>
        <FileBroken />
      </template>
      <div class="absolute-bottom headline ellipsis">
        {{ rec.headline }}
      </div>
    </q-img>
    <slot name="action"></slot>
    <q-card-section class="row justify-between">
      <span>
        <a href="/list" @click="app.searchBy({ nick: rec.nick })" class="link">{{ rec.nick }}</a
        >,
        <a
          href="/list"
          @click="app.searchBy({ year: rec.year, month: rec.month, day: rec.day })"
          class="link"
          >{{ rec.date ? formatDatum(rec.date, 'DD.MM.YYYY HH:mm') : '' }}</a
        >
      </span>

      <q-icon
        v-if="rec.loc"
        name="my_location"
        size="24px"
        target="blank"
        color="grey-7"
        @click.stop.prevent="openMaps(rec.loc)"
      />
    </q-card-section>
  </q-card>

  <q-card v-else :id="U + rec.filename" class="card" flat>
    <q-img loading="lazy" :ratio="5 / 4" :src="rec.url" no-spinner>
      <template #error>
        <FileBroken />
      </template>
    </q-img>
    <slot name="action"></slot>
  </q-card>
</template>

<script setup lang="ts">
import { U, formatDatum } from 'src/helpers'
import type { PhotoType } from 'src/helpers/models'
import { useAppStore } from 'src/stores/app'
import FileBroken from 'src/components/File-Broken.vue'

defineProps<{
  rec: PhotoType
}>()
const emit = defineEmits(['carousel-show'])
const app = useAppStore()

const openMaps = (loc: string) => {
  const url = `https://www.google.com/maps/search/?api=1&query=${loc}`
  window.open(url, '_blank')
}
</script>
