// src/components/TagsMerge.vue
<template>
  <AutoComplete
    :label="label"
    v-model="tagsToApply"
    :options="tagsValues"
    canadd
    multiple
    :hint="hint"
    @new-value="
      (value: string, done: (value: string) => void) => meta.addNewValue(value, 'tags', done)
    "
  />
</template>

<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { useValuesStore } from '../stores/values'
import AutoComplete from './AutoComplete.vue'

defineProps({
  label: {
    type: String,
    required: false,
    default: '',
  },
  hint: {
    type: String,
    required: false,
    default: '',
  },
})

const meta = useValuesStore()
const { tagsValues, tagsToApply } = storeToRefs(meta)
</script>

// src/components/TagsMerge.tsx
import React from 'react'
import { useValuesStore, selectTagsValues } from '../stores/valuesStore'
import AutoComplete from './AutoComplete'

interface TagsMergeProps {
  label?: string
  hint?: string
  className?: string
}

export const TagsMerge: React.FC<TagsMergeProps> = ({ label = '', hint = '', className = '' }) => {
  const meta = useValuesStore()
  const tagsValues = useValuesStore(selectTagsValues)
  const tagsToApply = useValuesStore((state) => state.tagsToApply)

  const handleTagsChange = (val: string | string[] | null) => {
    useValuesStore.setState({ tagsToApply: Array.isArray(val) ? val : [] })
  }

  const handleNewValue = (value: string, done: (val: string) => void) => {
    meta.addNewValue(value, 'tags', done)
  }

  return (
    <div className={className}>
      <AutoComplete
        label={label}
        modelValue={tagsToApply}
        onChange={handleTagsChange}
        options={tagsValues}
        canadd
        multiple
        hint={hint}
        onNewValue={handleNewValue}
      />
    </div>
  )
}

export default TagsMerge
