// src/components/atoms/AppDialog.tsx
import React, { Fragment } from 'react'
import { Dialog, DialogPanel, Transition, TransitionChild } from '@headlessui/react'

interface AppDialogProps {
  modelValue: boolean
  maxWidth?: string
  persistent?: boolean
  onChange?: (val: boolean) => void
  children?: React.ReactNode
}

export const AppDialog: React.FC<AppDialogProps> = ({
  modelValue,
  maxWidth = 'max-w-md',
  persistent = false,
  onChange,
  children,
}) => {
  const onClose = () => {
    if (persistent) return
    if (onChange) onChange(false)
  }

  return (
    <Transition show={modelValue} as={Fragment}>
      <Dialog as="div" className="relative z-[99999]" onClose={onClose}>
        {/* Backdrop */}
        <TransitionChild
          as={Fragment}
          enter="duration-200 ease-out"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="duration-150 ease-in"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <div className="fixed inset-0 bg-black/50 backdrop-blur-sm" />
        </TransitionChild>

        {/* Dialog panel wrapper */}
        <div className="fixed inset-0 overflow-y-auto">
          <div className="flex min-h-full items-center justify-center p-4">
            <TransitionChild
              as={Fragment}
              enter="duration-250 ease-out"
              enterFrom="opacity-0 scale-95 translate-y-4"
              enterTo="opacity-100 scale-100 translate-y-0"
              leave="duration-200 ease-in"
              leaveFrom="opacity-100 scale-100 translate-y-0"
              leaveTo="opacity-0 scale-95 translate-y-4"
            >
              <DialogPanel
                className={`w-full transform overflow-hidden rounded-2xl shadow-2xl transition-all bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 ${maxWidth}`}
              >
                {children}
              </DialogPanel>
            </TransitionChild>
          </div>
        </div>
      </Dialog>
    </Transition>
  )
}

export default AppDialog

// src/components/atoms/AppDialog.vue
<template>
  <TransitionRoot appear :show="modelValue" as="template">
    <Dialog as="div" class="relative z-[99999]" @close="$emit('update:modelValue', false)">
      <!-- Backdrop -->
      <TransitionChild
        as="template"
        enter="duration-200 ease-out"
        enter-from="opacity-0"
        enter-to="opacity-100"
        leave="duration-150 ease-in"
        leave-from="opacity-100"
        leave-to="opacity-0"
      >
        <div class="fixed inset-0 bg-black/50 backdrop-blur-sm" />
      </TransitionChild>

      <!-- Dialog panel -->
      <div class="fixed inset-0 overflow-y-auto">
        <div class="flex min-h-full items-center justify-center p-4">
          <TransitionChild
            as="template"
            enter="duration-250 ease-out"
            enter-from="opacity-0 scale-95 translate-y-4"
            enter-to="opacity-100 scale-100 translate-y-0"
            leave="duration-200 ease-in"
            leave-from="opacity-100 scale-100 translate-y-0"
            leave-to="opacity-0 scale-95 translate-y-4"
          >
            <DialogPanel
              :class="[
                'w-full transform overflow-hidden rounded-2xl shadow-2xl transition-all',
                'bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700',
                maxWidth,
              ]"
            >
              <slot />
            </DialogPanel>
          </TransitionChild>
        </div>
      </div>
    </Dialog>
  </TransitionRoot>
</template>

<script setup lang="ts">
import { TransitionRoot, TransitionChild, Dialog, DialogPanel } from '@headlessui/vue'

withDefaults(
  defineProps<{
    modelValue: boolean
    maxWidth?: string
    persistent?: boolean
  }>(),
  {
    maxWidth: 'max-w-md',
    persistent: false,
  },
)

defineEmits<{
  (e: 'update:modelValue', value: boolean): void
}>()
</script>
