// src/components/atoms/AppTabs.vue
<template>
  <!-- Headless UI TabGroup — replaces q-tabs / q-tab-panels pattern -->
  <TabGroup :selected-index="selectedIndex" @change="onTabChange" :vertical="vertical">
    <slot :TabList="TabList" :Tab="Tab" :TabPanels="TabPanels" :TabPanel="TabPanel" />
  </TabGroup>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { TabGroup, TabList, Tab, TabPanels, TabPanel } from '@headlessui/vue'

const props = defineProps<{
  modelValue: string
  tabs: Array<{ name: string; label?: string; icon?: string }>
  vertical?: boolean
}>()

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
}>()

const selectedIndex = computed(() => props.tabs.findIndex((t) => t.name === props.modelValue))

const onTabChange = (index: number) => {
  emit('update:modelValue', props.tabs[index]?.name ?? props.tabs[0].name)
}
</script>

// src/components/atoms/AppTabs.tsx
import React, { useMemo } from 'react'
import { TabGroup, TabList, Tab, TabPanels, TabPanel } from '@headlessui/react'

interface TabOption {
  name: string
  label?: string
  icon?: string
}

interface AppTabsProps {
  modelValue: string
  tabs: TabOption[]
  vertical?: boolean
  onChange?: (val: string) => void
  children?: (helpers: {
    TabList: typeof TabList
    Tab: typeof Tab
    TabPanels: typeof TabPanels
    TabPanel: typeof TabPanel
  }) => React.ReactNode
}

export const AppTabs: React.FC<AppTabsProps> = ({
  modelValue,
  tabs,
  vertical = false,
  onChange,
  children,
}) => {
  const selectedIndex = useMemo(() => {
    return tabs.findIndex((t) => t.name === modelValue)
  }, [tabs, modelValue])

  const onTabChange = (index: number) => {
    if (onChange && tabs[index]) {
      onChange(tabs[index].name)
    }
  }

  return (
    <TabGroup selectedIndex={selectedIndex >= 0 ? selectedIndex : 0} onChange={onTabChange} vertical={vertical}>
      {children && children({ TabList, Tab, TabPanels, TabPanel })}
    </TabGroup>
  )
}

export default AppTabs
