// src/components/sidebar/ManageSelection.vue
<template>
  <div class="bg-gray-50 dark:bg-gray-800 transition-colors p-2">
    <div v-if="user?.isAuthorized" class="mb-4">
      <AppInput v-model="headlineToApply" label="Headline to apply" clearable />
    </div>
    <TagsMerge v-if="user?.isAuthorized" class="mb-4" :label="`Tags to apply`" />

    <div v-if="selected.length > 0" class="flex flex-col gap-2" :class="{ 'gap-3': screen.gtSm }">
      <div class="text-xs text-center text-gray-500">{{ selected.length }} items selected</div>

      <AppButton
        v-if="tagsToApply && tagsToApply.length > 0"
        flat
        label="Merge Tags"
        icon="sym_r_merge"
        @click="applyTags"
        :disabled="busy"
        class="justify-end"
      />
      <AppButton
        v-if="headlineToApply"
        flat
        label="Apply Headline"
        icon="sym_r_find_replace"
        @click="applyHeadline"
        :disabled="busy"
        class="justify-end"
      />
      <AppButton
        color="negative"
        label="Delete Selected"
        icon="sym_r_delete"
        @click="deleteSelected"
        :disabled="busy"
        class="justify-end"
      />
      <AppButton
        flat
        label="Clear Selection"
        icon="sym_r_clear_all"
        @click="clearSelected"
        class="justify-end"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { useAppStore } from '../../stores/app'
import { useUserStore } from '../../stores/user'
import { useValuesStore } from '../../stores/values'
import TagsMerge from '../TagsMerge.vue'
import AppButton from '../atoms/AppButton.vue'
import AppInput from '../atoms/AppInput.vue'
import { useScreen } from '../../composables/useScreen'

const app = useAppStore()
const auth = useUserStore()
const meta = useValuesStore()
const screen = useScreen()

const { selected, busy } = storeToRefs(app)
const { user } = storeToRefs(auth)
const { headlineToApply, tagsToApply } = storeToRefs(meta)

const applyTags = async () => {
  for (const item of selected.value) {
    const rec = { ...item }
    rec.tags = Array.from(new Set([...(tagsToApply.value ?? []), ...(rec.tags ?? [])])).sort()
    await app.saveRecord(rec)
  }
  clearSelected()
}

const applyHeadline = async () => {
  if (!headlineToApply.value) return
  for (const item of selected.value) {
    const rec = { ...item }
    rec.headline = headlineToApply.value
    await app.saveRecord(rec)
  }
  clearSelected()
}

const deleteSelected = async () => {
  const toDelete = [...selected.value]
  for (const item of toDelete) {
    await app.deleteRecord(item)
  }
  clearSelected()
}

const clearSelected = () => {
  selected.value = []
}
</script>

// src/components/sidebar/ManageSelection.tsx
'use client'

import React from 'react'
import { useAppStore } from '../../stores/appStore'
import { useUserStore } from '../../stores/userStore'
import { useValuesStore } from '../../stores/valuesStore'
import TagsMerge from '../TagsMerge'
import AppButton from '../atoms/AppButton'
import AppInput from '../atoms/AppInput'
import { useScreen } from '../../composables/useScreen'

export const ManageSelection: React.FC = () => {
  const user = useUserStore((state) => state.user)
  const selected = useAppStore((state) => state.selected)
  const setSelected = useAppStore((state) => state.setSelected)
  const busy = useAppStore((state) => state.busy)
  const saveRecord = useAppStore((state) => state.saveRecord)
  const deleteRecord = useAppStore((state) => state.deleteRecord)

  const headlineToApply = useValuesStore((state) => state.headlineToApply)
  const tagsToApply = useValuesStore((state) => state.tagsToApply)
  const screen = useScreen()

  const handleHeadlineChange = (val: string) => {
    useValuesStore.setState({ headlineToApply: val })
  }

  const applyTags = async () => {
    for (const item of selected) {
      // Fetch fresh record from the objects store
      const objects = useAppStore.getState().objects
      const currentItem = objects.find((o) => o.filename === item.filename)
      if (!currentItem) continue

      const rec = { ...currentItem }
      rec.tags = Array.from(new Set([...(tagsToApply ?? []), ...(rec.tags ?? [])])).sort()
      await saveRecord(rec)
    }
    clearSelected()
  }

  const applyHeadline = async () => {
    if (!headlineToApply) return
    for (const item of selected) {
      const objects = useAppStore.getState().objects
      const currentItem = objects.find((o) => o.filename === item.filename)
      if (!currentItem) continue

      const rec = { ...currentItem }
      rec.headline = headlineToApply
      await saveRecord(rec)
    }
    clearSelected()
  }

  const deleteSelected = async () => {
    const toDelete = [...selected]
    for (const item of toDelete) {
      const objects = useAppStore.getState().objects
      const currentItem = objects.find((o) => o.filename === item.filename)
      if (!currentItem) continue

      await deleteRecord(currentItem)
    }
    clearSelected()
  }

  const clearSelected = () => {
    setSelected([])
  }

  return (
    <div className="bg-gray-55 dark:bg-gray-800 transition-colors p-2">
      {user?.isAuthorized && (
        <div className="mb-4">
          <AppInput
            modelValue={headlineToApply}
            onChangeValue={handleHeadlineChange}
            label="Headline to apply"
            clearable
          />
        </div>
      )}

      {user?.isAuthorized && <TagsMerge label="Tags to apply" className="mb-4" />}

      {selected.length > 0 && (
        <div className={`flex flex-col gap-2 ${screen.gtSm ? 'gap-3' : ''}`}>
          <div className="text-xs text-center text-gray-500">{selected.length} items selected</div>

          {tagsToApply && tagsToApply.length > 0 && (
            <AppButton
              flat
              label="Merge Tags"
              icon="sym_r_merge"
              onClick={applyTags}
              disabled={busy}
              className="justify-end"
            />
          )}

          {headlineToApply && (
            <AppButton
              flat
              label="Apply Headline"
              icon="sym_r_find_replace"
              onClick={applyHeadline}
              disabled={busy}
              className="justify-end"
            />
          )}

          <AppButton
            color="negative"
            label="Delete Selected"
            icon="sym_r_delete"
            onClick={deleteSelected}
            disabled={busy}
            className="justify-end"
          />

          <AppButton
            flat
            label="Clear Selection"
            icon="sym_r_clear_all"
            onClick={clearSelected}
            className="justify-end"
          />
        </div>
      )}
    </div>
  )
}

export default ManageSelection
