// src/components/Edit-Record.vue
<template>
  <q-dialog
    v-model="showEdit"
    :maximized="$q.screen.lt.md"
    transition-show="slide-up"
    transition-hide="slide-down"
    persistent
  >
    <q-card class="q-dialog-plugin full-width" style="max-width: 800px">
      <q-toolbar class="bg-white text-black row justify-between">
        <div>
          <q-btn color="primary" type="submit" label="Save" @click="onSubmit" />
          <q-btn
            v-if="user!.isAdmin"
            class="q-ml-sm gt-sm"
            flat
            label="Read Exif"
            @click="getExif"
          />
        </div>
        <div>{{ formatBytes(tmp.size) }} {{ tmp.dim }}</div>
        <div>
          <q-btn flat round dense icon="close" @click="onCancel" />
        </div>
      </q-toolbar>
      <q-card-section>
        <q-form
          autofocus
          autocorrect="off"
          autocapitalize="off"
          autocomplete="off"
          spellcheck="false"
          @submit="onSubmit"
        >
          <div class="row q-col-gutter-md">
            <div class="col-xs-12 col-sm-4 gt-xs">
              <q-img :ratio="1" :src="tmp.thumb ? tmp.thumb : tmp.url">
                <template #error>
                  <FileBroken />
                </template>
              </q-img>
            </div>
            <div class="col-xs-12 col-sm-8 col-8">
              <q-input
                v-model="tmp.headline"
                label="Headline"
                :hint="`Image without title is called '${CONFIG.noTitle}'`"
                autofocus
                clearable
              />
              <q-input v-model="tmp.filename" label="Filename" readonly />
              <Auto-Complete
                label="Author"
                v-model="tmp.email"
                :options="emailValues"
                hint="Admin can add freind's photo and email"
                :rules="[
                  (val: string) => !!val || 'Email is missing',
                  (val: string) => isValidEmail(val),
                ]"
              />
              <q-input v-model="tmp.date" label="Date taken">
                <template #prepend>
                  <q-icon name="event" class="cursor-pointer">
                    <q-popup-proxy cover transition-show="scale" transition-hide="scale">
                      <q-date v-model="tmp.date" :mask="CONFIG.dateFormat">
                        <div class="row items-center justify-end">
                          <q-btn v-close-popup label="Close" color="primary" flat />
                        </div>
                      </q-date>
                    </q-popup-proxy>
                  </q-icon>
                </template>
                <template #append>
                  <q-icon name="access_time" class="cursor-pointer">
                    <q-popup-proxy cover transition-show="scale" transition-hide="scale">
                      <q-time v-model="tmp.date" :mask="CONFIG.dateFormat" format24h>
                        <div class="row items-center justify-end">
                          <q-btn v-close-popup label="Close" color="primary" flat />
                        </div>
                      </q-time>
                    </q-popup-proxy>
                  </q-icon>
                </template>
              </q-input>
            </div>
            <div class="fit row nowrap">
              <div class="col-xs-11">
                <Auto-Complete
                  label="Tags"
                  v-model="tmp.tags"
                  :options="tagsValues"
                  canadd
                  multiple
                  clearable
                  class="col-auto"
                  :hint="tagsToApply && tagsToApply.length ? 'merge with ' + tagsToApply : ''"
                  @new-value="
                    (value: string, done: (value: string) => void) =>
                      meta.addNewValue(value, 'tags', done)
                  "
                >
                </Auto-Complete>
              </div>
              <div class="col self-center text-right">
                <q-icon
                  class="q-pl-sm q-pb-md cursor-pointer"
                  name="content_copy"
                  size="24px"
                  color="grey"
                  @click.stop.prevent="copyTags(tmp.tags || [])"
                />
                <q-icon
                  class="q-pl-sm q-pb-md cursor-pointer"
                  name="content_paste"
                  size="24px"
                  color="grey"
                  @click.stop.prevent="mergeTags(tmp.tags || [])"
                />
              </div>
            </div>
            <div class="col-xs-10"></div>

            <div class="col-xs-2 vertical-bottom text-right"></div>

            <div class="col-xs-12 col-sm-6">
              <Auto-Complete
                label="Camera Model"
                v-model="tmp.model"
                :options="modelValues"
                canadd
                @new-value="
                  (value: string, done: (value: string) => void) =>
                    meta.addNewValue(value, 'model', done)
                "
              />
            </div>
            <div class="col-xs-12 col-sm-6">
              <Auto-Complete
                label="Camera Lens"
                v-model="tmp.lens"
                :options="lensValues"
                canadd
                @new-value="
                  (value: string, done: (value: string) => void) =>
                    meta.addNewValue(value, 'lens', done)
                "
              />
            </div>
            <div class="col-xs-6 col-sm-4">
              <q-input v-model="tmp.focal_length" type="number" label="Focal length [mm]" />
            </div>

            <div class="col-xs-6 col-sm-4">
              <q-input v-model="tmp.iso" type="number" label="ISO [ASA]" />
            </div>
            <div class="col-xs-6 col-sm-4">
              <q-input v-model="tmp.aperture" type="number" step="0.1" label="Aperture" />
            </div>
            <div class="col-xs-6 col-sm-4">
              <q-input v-model="tmp.shutter" label="Shutter [s]" />
            </div>

            <div class="col-xs-6 col-sm-4">
              <q-input v-model="tmp.loc" label="Location [latitude, longitude]" clearable />
            </div>
            <div class="col-xs-6 col-sm-4 col-4 q-mt-sm">
              <q-checkbox v-model="tmp.flash" label="Flash fired?" />
            </div>
          </div>
        </q-form>
      </q-card-section>
    </q-card>
  </q-dialog>
</template>

<script setup lang="ts">
import { reactive } from 'vue'
import { CONFIG, U, formatBytes, textSlug, sliceSlug } from '../helpers'
import readExif from '../helpers/exif'
import { storeToRefs } from 'pinia'
import { useAppStore } from '../stores/app'
import { useValuesStore } from '../stores/values'
import { useUserStore } from '../stores/user'
import AutoComplete from './Auto-Complete.vue'
import FileBroken from './File-Broken.vue'
import type { PhotoType } from '../helpers/models'

const emit = defineEmits(['edit-ok'])
const props = defineProps({
  rec: Object,
})

const app = useAppStore()
const meta = useValuesStore()
const auth = useUserStore()
const tmp = reactive({ ...props.rec }) as PhotoType
const { showEdit, find } = storeToRefs(app)
const { tagsValues, tagsToApply, modelValues, lensValues, emailValues } = storeToRefs(meta)
const { user } = storeToRefs(auth)

const getExif = async () => {
  /**
   * Reread exif
   * See Add edit
   */
  const exif = await readExif(tmp.url)
  if (exif) {
    const tags = tmp.tags || []
    Object.assign(tmp, exif)
    // add flash tag if exif flash true
    if (tmp.flash && tags.indexOf('flash') === -1) {
      tags.push('flash')
    }
    tmp.tags = tags
  }
}
const isValidEmail = (val: string) => {
  const emailPattern =
    /^(?=[a-zA-Z0-9@._%+-]{6,254}$)[a-zA-Z0-9._%+-]{1,64}@(?:[a-zA-Z0-9-]{1,63}\.){1,8}[a-zA-Z]{2,63}$/
  return emailPattern.test(val) || 'Invalid email'
}

const copyTags = (source: string[]) => {
  tagsToApply.value = source
}
const mergeTags = (source: string[]) => {
  if (Array.isArray(source)) {
    tmp.tags = Array.from(new Set([...tagsToApply.value, ...source])).sort()
  } else {
    tmp.tags = tagsToApply.value
  }
}

window.onpopstate = function () {
  showEdit.value = false
}
const onCancel = () => {
  showEdit.value = false
}
const onSubmit = async () => {
  // if change date
  const datum = new Date(Date.parse((tmp.date as string) || ''))
  tmp.year = datum.getFullYear()
  tmp.month = datum.getMonth() + 1
  tmp.day = datum.getDate()
  // if change headline
  tmp.headline =
    tmp.headline === undefined || tmp.headline === null ? CONFIG.noTitle : tmp.headline.trim()
  tmp.text = sliceSlug(textSlug(tmp.headline))
  // if change tags
  tmp.tags = tmp.tags ? tmp.tags : []
  // if change email
  tmp.email = user.value!.email
  tmp.nick = user.value!.nick
  // add flash
  if (tmp.flash && tmp.tags.indexOf('flash') === -1) {
    tmp.tags.push('flash')
  }

  try {
    // set find on new added image
    if (!tmp.thumb) {
      find.value = Object.assign({}, { year: tmp.year, month: tmp.month, day: tmp.day })
    }

    await app.saveRecord(tmp)
    emit('edit-ok', U + tmp.filename)
    showEdit.value = false
  } catch (error) {
    console.error('Failed to save record:', error)
    // Optionally show error notification to user
    // notify.error('Failed to save changes')
  }
}
</script>

// src/components/dialog/EditRecord.tsx
'use client'

import React, { useState, useEffect, useMemo } from 'react'
import { useAppStore } from '../../stores/appStore'
import { useUserStore } from '../../stores/userStore'
import {
  useValuesStore,
  selectTagsValues,
  selectModelValues,
  selectLensValues,
  selectEmailValues,
} from '../../stores/valuesStore'
import { U, formatBytes, sliceSlug, getYouTubeId } from '../../helpers'
import CONFIG from '../../config'
import readExif from '../../helpers/exif'
import notify from '../../helpers/notify'
import type { PhotoType } from '../../helpers/models'
import AutoComplete from '../AutoComplete'
import FileBroken from '../FileBroken'
import AppDialog from '../atoms/AppDialog'
import AppButton from '../atoms/AppButton'
import AppInput from '../atoms/AppInput'
import AppCheckbox from '../atoms/AppCheckbox'
import AppIcon from '../atoms/AppIcon'

interface EditRecordProps {
  rec: PhotoType
  onEditOk?: (filename: string) => void
}

export const EditRecord: React.FC<EditRecordProps> = ({ rec, onEditOk }) => {
  const showEdit = useAppStore((state) => state.showEdit)
  const setShowEdit = useAppStore((state) => state.setShowEdit)
  const saveRecord = useAppStore((state) => state.saveRecord)
  const user = useUserStore((state) => state.user)
  const getNickByEmail = useUserStore((state) => state.getNickByEmail)

  const tagsValues = useValuesStore(selectTagsValues)
  const modelValues = useValuesStore(selectModelValues)
  const lensValues = useValuesStore(selectLensValues)
  const emailValues = useValuesStore(selectEmailValues)
  const tagsToApply = useValuesStore((state) => state.tagsToApply)
  const addNewValue = useValuesStore((state) => state.addNewValue)

  const [tmp, setTmp] = useState<PhotoType>({ ...rec })
  const [imgError, setImgError] = useState(false)
  const originalUrl = rec.url || ''

  // Sync state if rec prop changes
  useEffect(() => {
    setTmp({ ...rec })
  }, [rec])

  // Watch URL changes for videos to update thumb/filename automatically
  useEffect(() => {
    if (tmp.kind === 'video' && tmp.url) {
      const id = getYouTubeId(tmp.url)
      if (id) {
        setTmp((prev) => ({
          ...prev,
          filename: id,
          thumb: `https://img.youtube.com/vi/${id}/hqdefault.jpg`,
        }))
      } else {
        setTmp((prev) => ({ ...prev, thumb: '' }))
      }
    }
  }, [tmp.url, tmp.kind])

  const thumbUrl = useMemo(() => {
    if (tmp.thumb) return tmp.thumb
    if (tmp.kind === 'video') {
      const id = getYouTubeId(tmp.url)
      if (id) return `https://img.youtube.com/vi/${id}/hqdefault.jpg`
    }
    return tmp.url
  }, [tmp.thumb, tmp.url, tmp.kind])

  const getExif = async () => {
    const exif = await readExif(tmp.url)
    if (exif) {
      const tags = tmp.tags ? [...tmp.tags] : []
      if (exif.flash && !tags.includes('flash')) {
        tags.push('flash')
      }
      setTmp((prev) => ({
        ...prev,
        ...exif,
        tags,
      }))
    }
  }

  const isValidEmail = (val: string) => {
    const emailPattern =
      /^(?=[a-zA-Z0-9@._%+-]{6,254}$)[a-zA-Z0-9._%+-]{1,64}@(?:[a-zA-Z0-9-]{1,63}\.){1,8}[a-zA-Z]{2,63}$/
    return emailPattern.test(val) || 'Invalid email'
  }

  const copyTags = (source: string[]) => {
    useValuesStore.setState({ tagsToApply: source })
  }

  const mergeTags = (source: string[]) => {
    const arr = Array.isArray(source) ? source : []
    const merged = Array.from(new Set([...tagsToApply, ...arr])).sort()
    setTmp((prev) => ({ ...prev, tags: merged }))
  }

  const onCancel = () => {
    setShowEdit(false)
  }

  const onSubmit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault()

    const recordToSave = { ...tmp }
    const datum = new Date(Date.parse(recordToSave.date || ''))
    recordToSave.year = datum.getFullYear()
    recordToSave.month = datum.getMonth() + 1
    recordToSave.day = datum.getDate()
    recordToSave.headline = recordToSave.headline?.trim() || CONFIG.noTitle
    recordToSave.text = sliceSlug(recordToSave.headline)

    if (recordToSave.email !== user?.email && user?.isAdmin) {
      try {
        recordToSave.nick = await getNickByEmail(recordToSave.email)
      } catch (err) {
        notify({ type: 'negative', message: String(err) })
        return
      }
    } else {
      recordToSave.email = user?.email || ''
      recordToSave.nick = user?.nick || ''
    }

    if (recordToSave.kind === 'video' && recordToSave.url !== originalUrl) {
      const id = getYouTubeId(recordToSave.url)
      recordToSave.thumb = id ? `https://img.youtube.com/vi/${id}/hqdefault.jpg` : ''
    }

    recordToSave.tags = recordToSave.tags ? [...recordToSave.tags] : []
    if (recordToSave.flash && !recordToSave.tags.includes('flash')) {
      recordToSave.tags.push('flash')
    }

    // Email validation
    const emailValid = isValidEmail(recordToSave.email)
    if (typeof emailValid === 'string') {
      notify({ type: 'negative', message: emailValid })
      return
    }

    if (recordToSave.kind === 'video' && rec && recordToSave.filename !== rec.filename) {
      try {
        const { photoCollection } = await import('../../helpers/collections')
        const { doc, deleteDoc } = await import('firebase/firestore')
        await deleteDoc(doc(photoCollection, rec.filename))
        useAppStore.setState((state) => ({
          objects: state.objects.filter((x) => x.filename !== rec.filename),
        }))
      } catch (err) {
        console.error('Failed to delete old video document:', err)
      }
    }

    try {
      await saveRecord(recordToSave)
      if (onEditOk) {
        onEditOk(U + recordToSave.filename)
      }
      setShowEdit(false)
    } catch (err) {
      console.error('Failed to save record:', err)
    }
  }

  return (
    <AppDialog modelValue={showEdit} maxWidth="max-w-3xl" onChange={setShowEdit}>
      {/* Toolbar */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-gray-200 dark:border-gray-700">
        <div className="flex items-center gap-2">
          <AppButton type="button" color="primary" label="Save" onClick={() => onSubmit()} />
          {user?.isAdmin && tmp.kind !== 'video' && (
            <AppButton
              type="button"
              flat
              label="Read Exif"
              onClick={getExif}
              className="hidden sm:inline-flex"
            />
          )}
        </div>
        {tmp.kind !== 'video' && (
          <span className="text-xs text-gray-500 dark:text-gray-400">
            {formatBytes(tmp.size)} {tmp.dim}
          </span>
        )}
        <button
          className="text-gray-500 hover:text-gray-900 dark:hover:text-white transition-colors"
          onClick={onCancel}
        >
          <AppIcon name="close" className="w-6 h-6" />
        </button>
      </div>

      {/* Content */}
      <div className="p-4 overflow-y-auto max-h-[85vh]">
        <form
          autoCorrect="off"
          autoCapitalize="off"
          autoComplete="off"
          spellCheck="false"
          onSubmit={onSubmit}
        >
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {/* Thumbnail preview */}
            <div className="hidden sm:block sm:col-span-1">
              <div
                className="relative w-full overflow-hidden rounded-xl bg-gray-100 dark:bg-gray-800"
                style={{ paddingTop: '100%' }}
              >
                <img
                  src={thumbUrl}
                  alt={tmp.headline}
                  className="absolute inset-0 w-full h-full object-cover"
                  onError={() => setImgError(true)}
                />
                {imgError && <FileBroken />}
              </div>
            </div>

            {/* Fields */}
            <div className="flex flex-col gap-3 sm:col-span-1">
              <AppInput
                modelValue={tmp.headline}
                onChangeValue={(val) => setTmp((prev) => ({ ...prev, headline: val }))}
                label="Headline"
                hint={`Without title: '${CONFIG.noTitle}'`}
                clearable
                autoFocus
              />
              <AppInput modelValue={tmp.filename} label="Filename" readonly />
              {tmp.kind === 'video' && (
                <AppInput
                  modelValue={tmp.url}
                  onChangeValue={(val) => setTmp((prev) => ({ ...prev, url: val }))}
                  label="Video URL"
                  hint="YouTube link"
                  required
                />
              )}
              <AutoComplete
                label="Author"
                modelValue={tmp.email}
                onChange={(val) => setTmp((prev) => ({ ...prev, email: val as string }))}
                options={emailValues}
                hint="Admin can add friend's photo and email"
              />
              <AppInput
                modelValue={tmp.date}
                onChangeValue={(val) => setTmp((prev) => ({ ...prev, date: val }))}
                label="Date taken"
                type="datetime-local"
              />
            </div>

            {/* Tags row (full width) */}
            <div className="sm:col-span-2 flex items-start gap-2">
              <div className="flex-1">
                <AutoComplete
                  label="Tags"
                  modelValue={tmp.tags}
                  onChange={(val) =>
                    setTmp((prev) => ({ ...prev, tags: Array.isArray(val) ? val : [] }))
                  }
                  options={tagsValues}
                  canadd
                  multiple
                  hint={
                    tagsToApply && tagsToApply.length ? 'merge with ' + tagsToApply.join(', ') : ''
                  }
                  onNewValue={(value, done) => addNewValue(value, 'tags', done)}
                />
              </div>
              <div className="flex flex-col gap-1 mt-1">
                <button
                  type="button"
                  className="text-gray-400 hover:text-primary transition-colors p-1"
                  title="Copy tags"
                  onClick={() => copyTags(tmp.tags || [])}
                >
                  <AppIcon name="content_copy" className="w-5 h-5" />
                </button>
                <button
                  type="button"
                  className="text-gray-400 hover:text-primary transition-colors p-1"
                  title="Paste tags"
                  onClick={() => mergeTags(tmp.tags || [])}
                >
                  <AppIcon name="content_paste" className="w-5 h-5" />
                </button>
              </div>
            </div>

            {/* Photo-only EXIF fields */}
            {tmp.kind !== 'video' && (
              <>
                <AutoComplete
                  label="Camera Model"
                  modelValue={tmp.model}
                  onChange={(val) => setTmp((prev) => ({ ...prev, model: val as string }))}
                  options={modelValues}
                  canadd
                  onNewValue={(value, done) => addNewValue(value, 'model', done)}
                />
                <AutoComplete
                  label="Camera Lens"
                  modelValue={tmp.lens}
                  onChange={(val) => setTmp((prev) => ({ ...prev, lens: val as string }))}
                  options={lensValues}
                  canadd
                  onNewValue={(value, done) => addNewValue(value, 'lens', done)}
                />
                <AppInput
                  modelValue={tmp.focal_length}
                  onChangeValue={(val) =>
                    setTmp((prev) => ({ ...prev, focal_length: Number(val) }))
                  }
                  type="number"
                  label="Focal length [mm]"
                />
                <AppInput
                  modelValue={tmp.iso}
                  onChangeValue={(val) => setTmp((prev) => ({ ...prev, iso: Number(val) }))}
                  type="number"
                  label="ISO [ASA]"
                />
                <AppInput
                  modelValue={tmp.aperture}
                  onChangeValue={(val) => setTmp((prev) => ({ ...prev, aperture: Number(val) }))}
                  type="number"
                  step="0.1"
                  label="Aperture"
                />
                <AppInput
                  modelValue={tmp.shutter}
                  onChangeValue={(val) => setTmp((prev) => ({ ...prev, shutter: val }))}
                  label="Shutter [s]"
                />
                <AppInput
                  modelValue={tmp.loc}
                  onChangeValue={(val) => setTmp((prev) => ({ ...prev, loc: val }))}
                  label="Location [lat, lon]"
                  clearable
                />
                <div className="flex items-center gap-2 mt-2 col-span-2">
                  <AppCheckbox
                    modelValue={tmp.flash}
                    onChange={(val) => setTmp((prev) => ({ ...prev, flash: !!val }))}
                    label="Flash fired?"
                  />
                </div>
              </>
            )}
          </div>
        </form>
      </div>
    </AppDialog>
  )
}

export default EditRecord
